#server:
#  port: 8082
#
#spring:
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306/orderdb
#    username: root
#    password: root
#
#  sql:
#    init:
#      mode: always

spring:
  application:
    name: order-service

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO

